name: generator
publish_to: none

environment:
  # Change upper constraint to <4.0.0 when this PR is deployed to pub.dev:
  #   https://github.com/dart-lang/pub-dev/pull/6269
  sdk: '>=2.17.0 <3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  # Handle command-line arguments for development tooling.
  args: ^2.3.1

  # For generating Guid for parameterized types
  crypto: ^3.0.2

  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^2.2.4

  # Foreign Function Interface extension methods
  ffi: ^2.0.1

  # Help ensure that the code is well-written.
  lints: ^2.0.1

  # For calculating the relative file paths
  path: ^1.8.3

  # Running the test suite.
  test: ^1.22.1

  # Windows metadata for automatically generating API signatures. The
  # relationship between these two packages is tightly coupled, since this
  # package includes a specific version of the Win32 metadata, so we pin the
  # dependency by version to avoid surprising conflicts.
  winmd: 2.4.7

  # Win32 itself
  win32:
    path: ../..

dependency_overrides:
  win32:
    path: ../../
